// This file is @generated by prost-build.
pub mod gate {
    pub mod common {
        pub mod v1 {
            include!("gate.common.v1.rs");
        }
    }
    pub mod control {
        pub mod v1 {
            include!("gate.control.v1.rs");
        }
    }
    pub mod inference {
        pub mod v1 {
            include!("gate.inference.v1.rs");
        }
    }
    pub mod relay {
        pub mod v1 {
            include!("gate.relay.v1.rs");
        }
    }
}
