[toolchain]
channel = "nightly-2025-06-10"
components = ["rustfmt", "clippy", "rust-src", "rust-analyzer"]
targets = ["wasm32-unknown-unknown", "aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu"]
profile = "minimal"
